---
title: "Memory in Action 1: Sternberg and N-back"
output: 
  html_document:
    toc: true
date: "2023-04-13"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
library(tidyverse)
library(here)
library(ggthemes)
theme_set(theme_bw())
```

```{r, echo=T}
data_loc <- "data_1"

sternberg <- list.files(path=here(data_loc), pattern=".*sternberg.*csv") |> 
  map_df(~read_csv(here(data_loc,.))) |> 
  filter(!is.na(response_type)) |> 
  select(match_type, response_type, correct, rt, subject_id,trial_index) |> 
  mutate(rt=as.numeric(rt))


nback <- list.files(path=here(data_loc), pattern=".*nback.*csv") |> 
  map_df(~read_csv(here(data_loc,.))) |> 
  filter(!is.na(response_type)) |> 
  filter(exclude_trial==F) |> 
  select(phase, match_type, response_type, correct, rt, subject_id, trial_index) |> 
  mutate(rt=as.numeric(rt))
```

# Sternberg task

## Accuracy

```{r}

sternberg |> group_by(subject_id) |> 
  mutate(is.correct=as.numeric(correct)) |> 
  summarize(mean_correct=mean(is.correct)) |> 
  ggplot(aes(x="Sternberg task", y=mean_correct))+geom_jitter(width=.2, height=0)+
  stat_summary(fun.data = "mean_cl_boot", color="red")+
  labs(y="Percent correct", x="")


```

## Speed

```{r}

sternberg |> mutate(correct=ifelse(correct,"correct", "incorrect")) |> 
  ggplot(aes(x=rt, fill=correct))+
  geom_histogram()+facet_wrap(.~correct)+scale_fill_solarized()+
  theme(legend.position = "none")+
  labs(x="Reaction Time")

sternberg |> mutate(correct=ifelse(correct,"correct", "incorrect")) |> 
  ggplot(aes(x=correct, y=rt))+geom_jitter(width=.2, height=0, alpha=.1)+
  stat_summary(fun.data = "mean_cl_boot", color="red")+
  labs(y="Response time in ms", x="")

```

# N-back

## Accuracy


```{r}
# counts non response as false
nback |> group_by(phase, subject_id) |> 
  mutate(is.correct=as.numeric(correct)) |> 
  summarize(mean_correct=mean(is.correct)) |> 
  ggplot(aes(x=phase, y=mean_correct))+geom_jitter(width=.2, height=0, alpha=.3)+
  stat_summary(aes(color=phase),fun.data = "mean_cl_boot")+
  labs(y="Percent correct", x="")+
  theme(legend.position = "none")

# excluding non responses
nback |> filter(response_type!="NO_RESPONSE") |> 
  group_by(phase, subject_id) |> 
  mutate(is.correct=as.numeric(correct)) |> 
  summarize(mean_correct=mean(is.correct)) |> 
  ggplot(aes(x=phase, y=mean_correct))+geom_jitter(width=.2, height=0, alpha=.3)+
  stat_summary(aes(color=phase),fun.data = "mean_cl_boot")+
  labs(y="Percent correct", x="")+
  theme(legend.position = "none")
```

## Speed

```{r}

nback |> filter(response_type!="NO_RESPONSE") |> 
mutate(correct=ifelse(correct,"correct", "incorrect")) |> 
  ggplot(aes(x=rt, fill=phase))+
  geom_histogram()+facet_grid(.~phase)+scale_fill_solarized()+
  theme(legend.position = "none")+
  labs(x="Reaction Time")




nback|> mutate(correct=ifelse(correct,"correct", "incorrect")) |> 
  ggplot(aes(x=correct, y=rt, color=phase))+geom_jitter(width=.2, height=0, alpha=.01, color="black")+
  stat_summary(fun.data = "mean_cl_boot")+ facet_grid(.~phase)+
  labs(y="Response time in ms", x="")+theme(legend.position = "none")

```

```

```